#!/usr/bin/env bash
# transfer file from client to server

path_file=$1
ip_address=$2
username=$3
path_private_key=$4

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
	scp  -i "$path_private_key" "$path_file" "$username@$ip_address" -o "StrictHostKeyChecking no":~/;
fi
