#!/usr/bin/env bash
# installing Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
str="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "/server_name _;/a \\\tadd_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a $str" /etc/nginx/sites-enabled/default
sudo service nginx start
