#!/usr/bin/env bash
# file that installs a load balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 7737-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 7737-web-02 54.144.135.167:80 check\n\tserver 7737-web-01 54.144.133.202:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
