#!/usr/bin/env bash
# displays number from 1-100
# displays FizzBuzz when the number is a multiple of 3 and 5
# displays Fizz when number is multiple 3
# displays Buzz when the number is a multiple of 5
# otherwise, display the number

i=1
while test $i -ne 101; do
	if [ $((i%15)) -eq 0 ]; then
		echo FizzBuzz
	elif [ $((i%3)) -eq 0 ]; then
		echo Fizz
	elif [ $((i%5)) -eq 0 ]; then
		echo Buzz
	else
		echo $i
	fi
	i=$((i+1))
done
