#!/usr/bin/env bash
# Displays number 1-20
i=1
while test $i -le 20; do
	echo $i
	case $i in 4)
		echo bad luck from China
		;;
	9)
		echo bad luck from Japan
		;;
	17)
		echo bad luck from Italy
		;;
	*)
		;;
	esac
	i=$((i+1))
done
