#!/usr/bin/env bash
# installing the ufw firewall and setup a few rules on my web server
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
