#!/usr/bin/env bash
# port forwarding

str="#forwarding port 80 to 8080\n*nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT\n"
sudo sed -i "/# Don't delete these required lines, otherwise there will be errors/i$str" /etc/ufw/before.rules
sudo ufw enable
sudo service ufw restart
